### ISSUE TITLE
AERecorder initWithAudioController shows app as recording when in background

### ISSUE THREAD

**Issue by blixt** [TheAmazingAudioEngine/TheAmazingAudioEngine#130]
I am trying to make an app which will be ready to record whenever the user holds down a button. To do this, I'm creating an `AERecorder` instance beforehand so that the UI won't hang when the button is held down.

I have a few issues with this (one being that the UI becomes unresponsive for a second even if all I call is `AERecorderStartRecording`), but the most obvious one is that there's a red bar when the app is minimized after I've called `initWithAudioController` on an `AERecorder` instance (but before calling `prepareRecordingToFileAtPath`):

![2015-01-05 17 09 32](https://cloud.githubusercontent.com/assets/158591/5620875/10ab9ada-94fe-11e4-9691-13a575e2a787.png)

Is the intended use of the recorder class to only create it right before recording? Is there a better way?

**Comment by ndonald2** [comment]
+1 wondering about this as well.

**Comment by michaeltyson** [comment]
That red bar is there because the app is in the PlayAndRecord audio session category, and running in the background - which is what happens when you create an AEAudioController instance with input enabled. You can probably get around that somehow, perhaps by only creating the AEAudioController instance immediately before record, but it's always going to introduce a significant delay while the iOS audio system switches category.

I guess this is a security measure by Apple, to warn users when apps have the capability of listening to them in the background. Not much we can do about it though if you need instant record start, unless you want to disable background audio.
