### ISSUE TITLE
Q: channel "properties"

### ISSUE THREAD

**Issue by 32Beat** [TheAmazingAudioEngine/TheAmazingAudioEngine#207]
Is there ever a reason why a channel can --not-- set its volume, pan, muted, and playing state?

Considering that these "properties" are defined as optional protocol, is there a reason to be limited to read-only properties?

Is there a good reason for a relatively important element like a channel to be a protocol, instead of an object like the specific derivatives are anyway?

**Comment by 32Beat** [comment]
Please note: I'm asking since I might be missing the design objectives, not because I'm criticizing it.

**Comment by michaeltyson** [comment]
Read-only is just the minimum required state - you can make them readwrite if you like.

The reason it's a protocol is because Objective-C doesn't provide for 'mixin' class topologies, with multiple ancestors. If you have something you want to subclass but which you want to be a channel too, then it's really annoying to deal with if it has to be a subclass of some channel type as well. Protocols make things easier.

**Comment by 32Beat** [comment]
mixing class topologies... 

I'm really trying not to make this about religion, can you tell? ;-)

**Comment by michaeltyson** [comment]
We're developers, how could we possibly not make it about religion? ;-)

The idea with using protocols was to basically get out of developers' way. I couldn't think of any good reasons why it *needed* to be a class (there was no mandatory base functionality, for example), and making it a protocol means devs can do what they want. In my case, my track class happens to derive from a class that allows me to store the track in a NoSQL-like database system, because it's convenient and avoids a bunch of glue code.

**Comment by 32Beat** [comment]
Okay, I think I understand the reasoning. Perhaps abstraction of properties and behavior might have been a reason, since all channel objects pretty much would/should allow volume, panning, muting, etc., and some of that behavior might well be implemented in a superclass using vDSP to ensure it is consistent. 

However, since the render callbacks aren't strictly part of an object, it isn't necessary to be one. 

Having said that, though, I would like to opt for an AEGroupChannel object to be added, which basically would be a channel object which implements the internal group rendering and callback management. Because of the intricacies of the latter, it would be recommended to have it added in the framework, so it is not left as an exercise for an average developer like me...

An example of why I think all of this is a useful discussion:
I'm creating a ChannelViewController in the example code, the view looks like so:
![channelviewcontroller](https://cloud.githubusercontent.com/assets/786628/11399364/33c9f2d6-9387-11e5-9cf6-282fda5bc9ac.png)

It is initialized like so:
initWithAudioController: channel:(id<AEAudioPlayable>)

To refer back to the singleton AudioController problem: this initializer doesn't show that both the AudioController and channelobject are related, and that the existence of both these objects, and the connection between them, is assumed to exist during the lifetime of our viewcontroller.

For obvious reasons it could also be called a TrackViewController, and it could be initialized with some kind of track object. 

Now, clearly, the properties shown in the view; a play button, volume slider, rms levels, etc. equally apply to a group, so, with correct abstraction, I should be able to use the same ChannelViewController for a groupchannelobject. 

The AEGroupChannel object is obviously a type of mixer channel, and the AudioController could be a toplevel version of it.

**Comment by 32Beat** [comment]
The running result looks something like so:
![running](https://cloud.githubusercontent.com/assets/786628/11399808/faee5602-9389-11e5-94b0-fe60ae7cd857.png)

**Comment by 32Beat** [comment]
Also as a sidenote: I believe it would be useful to include the word Protocol in the name of the protocols.

**Comment by michaeltyson** [comment]
I don't disagree, although this sounds like a fairly academic argument so far, and the amount of work involved in making such a change really needs to be worth it. If you want to take a crack at it anyway, you're welcome to try and I'll consider merging it in - should probably talk about the approach you'd intend to take to make sure it fits, though.

As far as including the word "Protocol" in the protocols, that's really just a matter of taste. You're welcome to #define it to anything you like ;-)
