### ISSUE TITLE
Q: Filter code

### ISSUE THREAD

**Issue by 32Beat** [TheAmazingAudioEngine/TheAmazingAudioEngine#209]
In the AEAudioController->channelAudioProducer callback i see the following code. 

What is it trying to accomplish? 

```c
    // See if there's another filter
    for ( int i=channel->callbacks.count-1, filterIndex=0; i>=0; i-- ) {
        callback_t *callback = &channel->callbacks.callbacks[i];
        if ( callback->flags & kFilterFlag ) {
            if ( filterIndex == arg->nextFilterIndex ) {
                // Run this filter
                channel_producer_arg_t filterArg = *arg;
                filterArg.nextFilterIndex = filterIndex+1;
                return ((AEAudioFilterCallback)callback->callback)((__bridge id)callback->userInfo, (__bridge AEAudioController *)channel->audioController, &channelAudioProducer, (void*)&filterArg, &arg->timeStamp, *frames, audio);
            }
            filterIndex++;
        }
    }
```

**Comment by michaeltyson** [comment]
The filter chain operates recursively, in order to allow filters with a different number of input to output frames (time scalers, etc). The filters themselves are stored in an array, however: so this code manages mapping the array to recursive calls. You'll notice that AEAudioFilterCallback includes a producer/producerToken argument pair, which needs to be called in order to pull in the audio to be filtered. "producer" is actually a pointer to the channelAudioProducer function.

By the way: loving your attention to detail here. One of the reasons I made TAAE public back in the day was that I was hoping more eyeballs would help quality. Not many have delved as deeply as you though, so thanks, and keep it up.

**Comment by 32Beat** [comment]
Trying to rearrange the calls, I noticed that the producer/producerToken doesn't seem to allow the filter to call for a different TimeStamp. How is that accomplished? 

Would it be possible to request a FilePlayer for example for overlapping TimeStamps? 

e.g.: suppose we have an interpolation filter, it reduces a high samplerate to a lower samplerate. 
The timeframe requested from the filter is [0, ..., 10], 
the required source timeframe would be [-1, ..., 21], 
is that possible?

**Comment by michaeltyson** [comment]
Sorry about the delay on this one. I assume an answer's probably not useful any more; let me know if you're still interested and I'll put in a reply =)
